Repository jeong-sys/code-joa, pull requests merged in 2025-01, with the labels that each got.

#14 상품 추가
  ITEM.md
  README.md
Labels: ✨ Feature

#16 [#2] 상품 수정
  README.md
  UPDATEITEM.md
Labels: 📃 Docs, ✨ Feature

#15 [#3] 쇼핑몰 소개
  쇼핑몰소개
Labels: 📬 API, 📃 Docs, ✨ Feature

#18 [#7] 즐겨찾기
  favorites.md
Labels: 📬 API, ✨ Feature

#20 [#5] 상품 삭제
  DELETEITEM.md
Labels: 📃 Docs, ✨ Feature

#21 [#6] 상품 목록
  LIST.md
Labels: ✨ Feature

#26 [#10] 추천상품 조회
  recommend-item.md
Labels: 📬 API, ✨ Feature

#22 [#8] 상품 소개
  Introduce.md
Labels: ✨ Feature

#25 [#9] 검색
  search.md
Labels: ✨ Feature

#27 [#12] 푸터 개발
  footer.md
Labels: 🎨 Html&css
